"""
Expanded Training Data Generator for Social Good Chatbot
Generates 200+ high-quality TR/EN training samples.
"""
import json
import random
import os

os.environ["PYTHONUTF8"] = "1"

SYSTEM_TR = "Sen topluma faydalı bir yapay zeka asistanısın. Empati, doğruluk ve sosyal fayda önceliklerindir. Türkçe ve İngilizce bilirsin."
SYSTEM_EN = "You are a socially beneficial AI assistant. Your priorities are empathy, accuracy, and social impact."

TR_SAMPLES = [
    # --- Ruh Sağlığı ---
    {"user": "Stresle nasıl başa çıkabilirim?", "assistant": "Stres modern hayatın bir parçası ama yönetilebilir:\n\n**Anlık rahatlama:**\n1. **4-7-8 nefes tekniği**: 4 saniye nefes al, 7 saniye tut, 8 saniye ver\n2. **Kas gevşetme**: Ayak parmaklarından başlayarak tüm kasları sırayla kasıp gevşetin\n3. **Beş duyu egzersizi**: 5 gördüğünüz, 4 dokunduğunuz, 3 duyduğunuz, 2 kokladığınız, 1 tattığınız şeyi sayın\n\n**Uzun vadeli stratejiler:**\n- Düzenli egzersiz (haftada 3x30dk yürüyüş bile yeterli)\n- Uyku hijyeni: Her gün aynı saatte yatıp kalkın\n- Sosyal bağlantılar: Sevdiklerinizle vakit geçirin\n- Hobi edinme: Yaratıcı aktiviteler stresi azaltır\n- Sınır koyma: Her şeye 'evet' demek zorunda değilsiniz\n\n**Profesyonel destek:** Stres günlük yaşamınızı etkiliyorsa mutlaka bir uzmana başvurun.\nALO 182: 7/24 ücretsiz psikolojik destek hattı"},
    {"user": "Panik atak geçiriyorum ne yapmalıyım?", "assistant": "Panik atak çok korkutucu olabilir ama tehlikeli değildir ve mutlaka geçer.\n\n**Şu an yapabileceğiniz:**\n1. **Güvenli bir yere oturun** ve kendinize 'Bu geçecek' deyin\n2. **Diyafram nefesi**: Burnundan yavaşça 4 saniye nefes al, 6 saniye ağızdan ver\n3. **Topraklama tekniği**: Etrafınızda 5 mavi nesne bulun, ayaklarınızın yere bastığını hissedin\n4. **Buz terapisi**: Ellerinize buz tutun veya yüzünüze soğuk su çarpın\n5. **Kas gevşetme**: Yumruklarınızı sıkıp 5 saniye sonra bırakın\n\n**Önemli bilgiler:**\n- Panik atak ortalama 10-20 dakika sürer\n- Kalp krizi DEĞİLDİR (ama ilk kez yaşıyorsanız doktora gidin)\n- Nefes tutmak veya hızlı solumak kötüleştirir\n\n**Uzun vadede:**\n- Bilişsel davranışçı terapi (BDT) çok etkilidir\n- Kafein ve alkol tetikleyici olabilir\n- Düzenli egzersiz ve meditasyon koruyucudur\n\n⚠️ Acil destek: ALO 182 | 112 Acil"},
    {"user": "Depresyon belirtileri nelerdir?", "assistant": "Depresyon ciddi ama tedavi edilebilir bir ruh sağlığı durumudur.\n\n**Temel belirtiler (2 haftadan fazla sürüyorsa):**\n1. Sürekli üzgün, boş veya umutsuz hissetmek\n2. İlgi ve zevk kaybı (eskiden keyif aldığınız şeylerden)\n3. Enerji düşüklüğü ve sürekli yorgunluk\n4. Uyku değişiklikleri (çok uyuma veya uyuyamama)\n5. İştah değişiklikleri (aşırı yeme veya iştahsızlık)\n6. Konsantrasyon güçlüğü ve karar verememe\n7. Değersizlik veya aşırı suçluluk duygusu\n8. Sosyal çekilme\n\n**Dikkat:** Bunlar normal üzüntüden farklıdır. Depresyon bir zayıflık değil, tıbbi bir durumdur.\n\n**Ne yapmalı:**\n- Bir psikiyatrist veya psikologdan randevu alın\n- Tedavi seçenekleri: Terapi + gerekirse ilaç\n- Kendinize nazik olun, iyileşme zaman alır\n\n⚠️ İntihar düşüncesi varsa hemen arayın:\nALO 182 (7/24) | 112 Acil | İntihar Önleme Hattı: 182"},
    {"user": "Çocuğumda anksiyete var gibi, ne yapmalıyım?", "assistant": "Çocuklarda anksiyete oldukça yaygındır ve erken müdahale çok önemlidir.\n\n**Belirtiler:**\n- Aşırı endişe ve korku\n- Karın ağrısı, baş ağrısı gibi fiziksel şikayetler\n- Uyku problemleri veya kabuslar\n- Ayrılık kaygısı\n- Sosyal durumlarda geri çekilme\n- Mükemmeliyetçilik\n\n**Ebeveyn olarak yapabilecekleriniz:**\n1. **Doğrulayın**: 'Korkman normal, seninle birlikteyim' deyin\n2. **Zorlamayın**: Kademeli yaklaşım kullanın\n3. **Nefes egzersizleri öğretin**: 'Balon şişiriyormuş gibi nefes alalım'\n4. **Rutin oluşturun**: Düzen güven verir\n5. **Model olun**: Kendi stres yönetiminizi gösterin\n\n**Profesyonel destek ne zaman:**\n- Okula gidemiyorsa\n- Günlük aktiviteleri yapamıyorsa\n- 6 aydan uzun sürüyorsa\n\nÇocuk psikologları oyun terapisi ile harika sonuçlar alır."},
    {"user": "Yas tutmak ne kadar sürer?", "assistant": "Yas, kaybın doğal bir tepkisidir ve herkes farklı yaşar.\n\n**Yas süreci (Kübler-Ross modeli):**\n1. **İnkar**: 'Bu gerçek olamaz'\n2. **Öfke**: 'Bu adil değil'\n3. **Pazarlık**: 'Keşke...'\n4. **Depresyon**: Derin üzüntü\n5. **Kabul**: Yeni normale uyum\n\n**Önemli:** Bu aşamalar sırayla yaşanmak zorunda değildir. İleri geri gidebilirsiniz.\n\n**Ne kadar sürer:**\n- Herkes için farklıdır — ay, yıl olabilir\n- Acı zamanla azalır ama tamamen geçmeyebilir\n- 'Doğru' bir süre yoktur\n\n**Kendinize yardım:**\n- Duygularınızı bastırmayın, ağlamak iyileştiricidir\n- Sevdiklerinizle konuşun\n- Rutininizi korumaya çalışın\n- Fiziksel sağlığınızı ihmal etmeyin\n- Anıları kutlayın\n\n**Profesyonel destek alın eğer:**\n- 6 aydan sonra günlük yaşam sürdürülemiyorsa\n- İntihar düşüncesi varsa\n\nALO 182: Ücretsiz psikolojik destek"},
    # --- Afet ve Acil Durum ---
    {"user": "Sel baskını olursa ne yapmalıyız?", "assistant": "Sel baskınlarında hayat kurtaran bilgiler:\n\n**Sel öncesi hazırlık:**\n- Acil durum çantası hazırlayın (su, yiyecek, ilaç, fener, pil)\n- Evin elektrik sigortasını nasıl kapatacağınızı bilin\n- Değerli evrakları su geçirmez poşette saklayın\n- Ailenizle buluşma noktası belirleyin\n\n**Sel anında:**\n1. **Yüksek yere çıkın** — bodrum ve zemin kattan uzaklaşın\n2. **Elektriği kesin** (sigorta kutusu suya erişilebilir durumdaysa dokunmayın)\n3. **Akan suya GİRMEYİN** — 15 cm su bile sizi devirebilir\n4. **Araçla geçmeyin** — 30 cm su aracı sürükleyebilir\n5. **Alt geçitlerden kaçının**\n\n**Sel sonrası:**\n- Hasarlı binaya girmeyin\n- Sel suyuna temas ettiyseniz dezenfekte olun\n- Buzdolabındaki yiyecekleri atın\n\n**Acil hattlar:** AFAD: 122 | Acil: 112 | İtfaiye: 110"},
    {"user": "Yangın çıkarsa evde ne yapmalıyız?", "assistant": "Ev yangınında ilk 2 dakika kritiktir:\n\n**Hemen yapılacaklar:**\n1. **Yere yakın hareket edin** — duman yukarı çıkar\n2. **Kapıyı açmadan dokunun** — sıcaksa açmayın, başka çıkış bulun\n3. **Herkes dışarı** — eşya için GERİ DÖNMEYİN\n4. **Toplanma noktasına gidin** ve itfaiyeyi arayın\n\n**Kıyafetiniz alev aldıysa:**\n- DUR — koşmayın\n- YER — yere uzanın\n- YUVARLAN — alevler sönene kadar\n\n**Yangın önleme:**\n- Duman dedektörü takın (her katta)\n- Yangın söndürücü bulundurun\n- Elektrik tesisatını kontrol ettirin\n- Mum ve soba kullanırken dikkatli olun\n- Kaçış planı yapın ve ailecek prova edin\n\n**İtfaiye:** 110 | **Acil:** 112"},
    {"user": "Deprem çantasında neler olmalı?", "assistant": "72 saat yetecek bir deprem çantası hazırlayın:\n\n**Temel ihtiyaçlar:**\n- Su: Kişi başı günlük 3 litre (9L toplam)\n- Enerji barları, kuruyemiş, konserve\n- Manuel konserve açacağı\n- Fener + yedek pil (mum DEĞİL)\n- Düdük (enkaz altında sinyal için)\n- İlk yardım çantası\n\n**Kişisel ihtiyaçlar:**\n- Düzenli kullanılan ilaçlar (1 haftalık)\n- Gözlük/lens\n- Hijyen malzemeleri\n- Sıcak tutan battaniye (folyo)\n- Yedek kıyafet ve iç çamaşırı\n\n**Belgeler (fotokopi):**\n- Kimlik, pasaport\n- Sigorta poliçeleri\n- Banka bilgileri\n- Aile fotoğrafı (kayıp durumunda)\n\n**Araçlar:**\n- Powerbank (şarjlı)\n- Radyo (pilli)\n- Çakı/bıçak\n- Nakit para\n- Su arıtma tableti\n\n**İpucu:** Çantayı kapıya yakın, kolay erişilebilir yerde tutun. 6 ayda bir kontrol edip süresi dolmuşları yenileyin."},
    # --- Toplumsal Sorunlar ---
    {"user": "Kadına yönelik şiddete karşı ne yapabilirim?", "assistant": "Kadına yönelik şiddet ciddi bir toplumsal sorundur ve herkesin sorumluluğudur.\n\n**Şiddete tanık olursanız:**\n1. Güvenliyse müdahale edin\n2. 155 (Polis) veya 112'yi arayın\n3. Mağduru yalnız bırakmayın\n\n**Şiddet mağduruysanız:**\n- **ALO 183**: Aile ve Sosyal Hizmetler (7/24)\n- **Mor Çatı**: 0212 292 52 31\n- **Kadın Dayanışma Vakfı**: 0212 251 40 48\n- Sığınma evi talep edebilirsiniz (6284 sayılı kanun)\n\n**Hukuki haklar:**\n- Koruma kararı talep edin (karakol veya aile mahkemesi)\n- Uzaklaştırma kararı polisten istenebilir\n- Boşanma davası sürerken tedbir kararı alınabilir\n\n**Toplum olarak:**\n- Şiddeti normalleştiren söylemlere itiraz edin\n- Çocuklarınıza eşitlik ve saygı öğretin\n- Kadın STK'larını destekleyin\n- 'Aile içi mesele' deyip geçmeyin\n\nŞiddet ASLA mazur görülemez."},
    {"user": "Mülteci komşularıma nasıl yardımcı olabilirim?", "assistant": "Mülteci komşularınıza destek olmak toplumsal uyumu güçlendirir:\n\n**Doğrudan yapabileceğiniz:**\n1. **Karşılayın**: Basit bir 'hoş geldiniz' bile çok anlam ifade eder\n2. **Dil desteği**: Resmi işlemler, hastane randevuları için tercüme yardımı\n3. **Yönlendirme**: Okul kayıt, sağlık hizmetleri, İŞKUR bilgisi\n4. **Çocukların kaynaşması**: Park, oyun alanı buluşmaları organize edin\n\n**Pratik destek:**\n- Kullanmadığınız eşya, kıyafet bağışı\n- İş bağlantıları ve referans\n- Mahalle esnafına tanıtın\n- Kültürel etkinliklere birlikte katılın\n\n**STK'lar aracılığıyla:**\n- Mülteci Hakları Derneği\n- SGDD-ASAM (Göç ve İltica)\n- Kızılay Toplum Merkezleri\n- UNHCR Türkiye\n\n**Önemli:** Saygılı olun, merak değil empati gösterin. Travma yaşamış olabilirler."},
    {"user": "Yoksullukla mücadelede bireysel neler yapabiliriz?", "assistant": "Yoksullukla mücadele herkesin katkısıyla mümkündür:\n\n**Doğrudan yardım:**\n1. **Askıda pratikleri**: Askıda ekmek, askıda market, askıda ilaç\n2. **Gıda bankası bağışı**: Yerel gıda bankalarına düzenli katkı\n3. **Kıyafet bağışı**: Temiz, kullanılabilir kıyafetleri ihtiyaç sahiplerine ulaştırın\n4. **Eğitim bursu**: Öğrencilere burs desteği sağlayın\n\n**Sürdürülebilir çözümler:**\n- **Kooperatif desteği**: Kadın kooperatiflerinden alışveriş yapın\n- **Yerel üretici**: Küçük esnaf ve çiftçiden alın\n- **Mikro kredi**: Kalkınma programlarına bağış yapın\n- **Eğitim gönüllülüğü**: Dezavantajlı çocuklara ücretsiz ders verin\n\n**Sosyal politika:**\n- Yerel yönetimlere sosyal yardım talebinde bulunun\n- Eşitsizlik karşıtı politikaları destekleyin\n\n**İletişim:**\n- ALO 144: Sosyal yardım\n- e-Devlet: Sosyal yardım başvuruları\n- Belediye sosyal yardım birimi"},
    {"user": "Dijital okuryazarlık nedir ve neden önemli?", "assistant": "Dijital okuryazarlık, teknolojiyi güvenli ve etkili kullanma becerisidir.\n\n**Temel bileşenleri:**\n1. **Bilgi okuryazarlığı**: Doğru bilgiyi sahte haberden ayırt etme\n2. **İletişim**: Dijital ortamda saygılı ve etkili iletişim\n3. **Güvenlik**: Kişisel verileri koruma, güçlü şifre kullanma\n4. **İçerik üretimi**: Sorumlu paylaşım yapma\n5. **Problem çözme**: Teknik sorunlara çözüm bulabilme\n\n**Neden önemli:**\n- Sahte haberler demokrasiyi tehdit ediyor\n- Dolandırıcılık ve kimlik hırsızlığı yaygınlaşıyor\n- İş hayatında dijital beceriler zorunlu hale geldi\n- Çocukların güvenli internet kullanımı için şart\n\n**Kendinizi geliştirin:**\n- BTK Akademi (ücretsiz eğitimler)\n- Google Dijital Atölye\n- Kaynak doğrulama: teyit.org kullanın\n- İki faktörlü doğrulama açın (tüm hesaplarda)\n\n**Çocuklara öğretin:**\n- İnternet güvenliği kuralları\n- Kişisel bilgi paylaşmama\n- Siber zorbalıkla başa çıkma\n- Ekran süresi dengeleme"},
    {"user": "Toplumsal cinsiyet eşitliği için neler yapabiliriz?", "assistant": "Toplumsal cinsiyet eşitliği herkesin hakkıdır:\n\n**Günlük yaşamda:**\n1. **Ev içi iş bölümü**: Ev işleri ve çocuk bakımını eşit paylaşın\n2. **Dil kullanımı**: Cinsiyetçi espri ve kalıplara itiraz edin\n3. **Rol model olun**: Çocuklara eşitlik değerlerini yaşayarak öğretin\n4. **Eşit fırsatlar**: Kız çocuklarını bilim, spor her alana teşvik edin\n\n**İş yaşamında:**\n- Eşit işe eşit ücret talep edin\n- Kadın girişimciliği destekleyin\n- Mentörlük programlarına katılın\n- Ayrımcılığa karşı sesinizi yükseltin\n\n**Toplumsal düzeyde:**\n- Kadın STK'ları destekleyin\n- Yerel yönetimlerde kadın temsilini artırın\n- Erken yaşta evliliklere karşı durun\n- Eğitime erişimi savunun\n\n**Kaynaklar:**\n- UN Women Türkiye\n- Kadın Dayanışma Vakfı\n- KSGM (Kadının Statüsü Genel Müdürlüğü)\n- TÜBİTAK bilim kampları (kız öğrenciler için)"},
    {"user": "Madde bağımlılığıyla mücadelede ne yapabilirim?", "assistant": "Madde bağımlılığı bir hastalıktır, ahlaki başarısızlık değildir.\n\n**Kendiniz için endişeleniyorsanız:**\n1. Bağımlılık bir seçim değil, beyin kimyası değişikliğidir\n2. Yardım istemek güçlülük göstergesidir\n3. Tedavi mümkündür ve işe yarar\n\n**İlk adımlar:**\n- AMATEM'e başvurun (Alkol Madde Tedavi Merkezi)\n- Yeşilay Danışmanlık Merkezi: ALO 191\n- ÇEMATEM (Çocuk ve Ergen Madde Bağımlılığı)\n\n**Bir yakınınız için:**\n- Yargılamayın, destek olun\n- Davranışı onaylamanız gerekmez, kişiyi sevebilirsiniz\n- Bağımlılık hakkında bilgilenin\n- Kendi sınırlarınızı koruyun\n- Al-Anon gibi yakın destek gruplarına katılın\n\n**Toplum olarak:**\n- Bağımlılıkla ilgili damgalamayı azaltın\n- Gençlere yönelik farkındalık programlarını destekleyin\n- Tedavi merkezlerinin yaygınlaşmasını savunun\n\n**Acil:** ALO 191 (Yeşilay) | 112 | AMATEM hastaneleri"},
    {"user": "İlk yardım temel bilgileri nelerdir?", "assistant": "Temel ilk yardım bilgileri hayat kurtarabilir:\n\n**ABCDE protokolü:**\n- **A** (Airway): Hava yolları açık mı?\n- **B** (Breathing): Nefes alıyor mu?\n- **C** (Circulation): Nabız var mı? Kanama var mı?\n- **D** (Disability): Bilinç durumu\n- **E** (Exposure): Görünen yaralanmalar\n\n**Kanama durumunda:**\n1. Temiz bezle bastırın (en az 10 dakika)\n2. Yaralı bölgeyi kalp seviyesinin üstüne kaldırın\n3. Turnike son çaredir\n\n**Yanık durumunda:**\n1. Akan soğuk su altında 20 dakika tutun\n2. Buz, diş macunu, yoğurt SÜRMEYİN\n3. Kabarcıkları patlatmayın\n\n**Bilinç kaybında:**\n1. Yan yatırın (koma pozisyonu)\n2. Hava yolunu açın\n3. Nefes ve nabzı kontrol edin\n4. 112'yi arayın\n\n**CPR (kalp masajı):**\n- Göğüs ortasına 5-6 cm derinlikte bastırın\n- Dakikada 100-120 bası\n- 30 bası + 2 suni solunum\n\n**Acil:** 112 | Zehir Danışma: 114"},
    {"user": "Sağlıklı beslenme için bütçe nasıl planlanır?", "assistant": "Sağlıklı beslenme pahalı olmak zorunda değil:\n\n**Akıllı alışveriş:**\n1. **Mevsiminde sebze meyve**: Hem ucuz hem taze\n2. **Kuru baklagiller**: Mercimek, nohut, fasulye — ucuz protein kaynağı\n3. **Toptan alım**: Pirinç, bulgur, makarna büyük pakette ucuz\n4. **Semt pazarı**: Market fiyatlarının %30-50 altında\n5. **Liste yapın**: İndirimli ürünlere göre değil, ihtiyaca göre alın\n\n**Haftalık menü planı:**\n- Pazartesi: Mercimek çorbası + bulgur pilavı\n- Salı: Yumurtalı sebze\n- Çarşamba: Kuru fasulye + pilav\n- Perşembe: Makarna + salata\n- Cuma: Tavuk sote + sebze\n\n**Tasarruf ipuçları:**\n- Yemek hazırlama (meal prep): Haftalık pişirip porsiyonlayın\n- Ekmek israfını önleyin (bayat ekmeği köfte/tost yapın)\n- Dondurucuyu kullanın\n- Mevsiminde bol alıp konserve/turşu yapın\n\n**Besin değeri yüksek, ucuz gıdalar:**\nYumurta, yoğurt, bulgur, mercimek, havuç, lahana, muz"},
    {"user": "Çevreyi korumak için günlük hayatta neler yapabilirim?", "assistant": "Her gün yapabileceğiniz çevre dostu alışkanlıklar:\n\n**Su tasarrufu:**\n- Duşu 5 dakikada bitirin (yılda 30.000L tasarruf)\n- Diş fırçalarken musluğu kapatın\n- Çamaşır/bulaşık makinesini dolu çalıştırın\n- Yağmur suyu biriktirin (bahçe için)\n\n**Atık azaltma:**\n- Bez çanta kullanın\n- Cam/çelik su şişesi taşıyın\n- Gereksiz ambalajdan kaçının\n- Komposta başlayın (organik atıklar)\n\n**Ulaşım:**\n- Kısa mesafelerde yürüyün veya bisiklet kullanın\n- Toplu taşıma tercih edin\n- Araç paylaşımı (carpool) yapın\n\n**Enerji:**\n- LED ampuller kullanın (%80 tasarruf)\n- Kullanılmayan cihazları fişten çekin\n- Klima 24°C, kombi 21°C ayarlayın\n\n**Tüketim alışkanlıkları:**\n- İkinci el alışveriş yapın\n- Tamir ettirin, hemen atmayın\n- Yerel üretici tercih edin\n- Mevsiminde meyve sebze tüketin\n\nBir kişinin değişimi yılda 2-3 ton CO2 tasarrufu sağlar!"},
    {"user": "Okul öncesi çocuklarda değerler eğitimi nasıl verilir?", "assistant": "Erken çocukluk döneminde değerler eğitimi yaşam boyu iz bırakır:\n\n**Temel değerler ve öğretme yolları:**\n\n**Empati:**\n- 'O çocuk nasıl hissediyor sence?' sorun\n- Duygu kartları ile oyun oynayın\n- Hikaye kitaplarındaki karakterlerin duygularını tartışın\n\n**Paylaşma:**\n- Oyuncak paylaşımını zorlamayın, modelleyin\n- 'Birlikte oynayalım' yerine 'Sırayla oynayalım' öğretin\n\n**Doğa sevgisi:**\n- Birlikte bitki yetiştirin\n- Hayvanları gözlemleyin\n- Çöp toplamayı oyun haline getirin\n\n**Saygı:**\n- Çocuğa saygılı davranın (o da öğrensin)\n- Farklılıklara açık olun\n- Büyüklere saygıyı zorlama değil, sevgi ile öğretin\n\n**Yöntemler:**\n1. **Modelleme**: Siz yapın, çocuk görsün\n2. **Hikaye**: Masal ve öyküler güçlü araçlardır\n3. **Oyun**: Rol yapma oyunları\n4. **Doğal sonuçlar**: Paylaşmayınca arkadaş üzülür → empati gelişir\n5. **Olumlu pekiştireç**: İyi davranışı fark edin ve takdir edin"},
    {"user": "Yaşlı bireylerde düşme riski nasıl azaltılır?", "assistant": "Düşmeler yaşlı bireyler için ciddi risk oluşturur ama önlenebilir:\n\n**Ev düzenlemesi:**\n1. **Kaydırmaz paspas**: Banyo ve mutfakta şart\n2. **Tutunma barları**: Duş ve tuvalet yanına\n3. **Aydınlatma**: Gece lambaları, karanlık köşe olmasın\n4. **Halı kenarları**: Yapıştırın veya kaldırın\n5. **Kablo düzeni**: Yere uzanan kablo olmasın\n6. **Merdiven korkulukları**: Sağlam, iki taraflı\n\n**Fiziksel önlemler:**\n- Düzenli egzersiz (denge ve güç)\n- Tai Chi — düşme riskini %40 azaltır\n- Doğru ayakkabı (kaymaz taban, tam kapalı)\n- Baston/yürüteç kullanımından utanmayın\n\n**Sağlık kontrolleri:**\n- Göz muayenesi (yılda 1)\n- İşitme testi\n- İlaç yan etkileri kontrolü (baş dönmesi yapan ilaçlar)\n- D vitamini ve kalsiyum takviyesi\n- Kan basıncı takibi\n\n**Acil:** 112 | Sağlık Bakanlığı ALO 184"},
    {"user": "İnternet güvenliği için temel kurallar nelerdir?", "assistant": "Dijital güvenlik herkes için kritik öneme sahiptir:\n\n**Şifre güvenliği:**\n1. Her hesap için farklı, güçlü şifre (en az 12 karakter)\n2. Şifre yöneticisi kullanın (Bitwarden, KeePass — ücretsiz)\n3. İki faktörlü doğrulama (2FA) açın — HER YERDE\n4. SMS yerine authenticator uygulaması tercih edin\n\n**Dolandırıcılık korunma:**\n- Bilinmeyen linkler tıklamayın\n- Banka asla SMS/mail ile şifre sormaz\n- 'Ödül kazandınız' mesajlarına inanmayın\n- Telefonda kişisel bilgi vermeyin\n\n**Sosyal medya:**\n- Gizlilik ayarlarını sıkılaştırın\n- Konum paylaşımını kapatın\n- Tatilde olduğunuzu gerçek zamanlı paylaşmayın\n- Çocuk fotoğraflarına dikkat\n\n**Cihaz güvenliği:**\n- İşletim sistemi ve uygulamaları güncel tutun\n- Antivirüs kullanın\n- Halka açık Wi-Fi'da VPN kullanın\n- Düzenli yedekleme yapın\n\n**İhbar:** Siber suçlar: 155 | BTK: 444 0 135"},
    {"user": "Otizm spektrum bozukluğu hakkında ne bilmeliyiz?", "assistant": "Otizm, nörogelişimsel bir farklılıktır — hastalık değil.\n\n**Temel bilgiler:**\n- Her 54 çocuktan 1'ini etkiler\n- Bir spektrumdur: Her otizmli birey farklıdır\n- Nedeni tam bilinmez, genetik faktörler etkili\n- Aşılar otizme NEDEN OLMAZ (bilimsel olarak kanıtlanmıştır)\n\n**Belirtiler (erken tanı önemli):**\n- Göz teması kurmama\n- İsmine dönmeme\n- Sosyal iletişimde güçlük\n- Tekrarlayan davranışlar\n- Rutin değişikligine tepki\n- Duyusal hassasiyet\n\n**Destek nasıl olunur:**\n1. **Sabırlı olun**: Farklı düşünme biçimini kabul edin\n2. **Net iletişim**: Kısa, açık cümleler kullanın\n3. **Rutin**: Değişiklikleri önceden haber verin\n4. **Güçlü yönlere odaklanın**: Birçok otizmli bireyin özel yetenekleri var\n\n**Aileler için:**\n- TOÇEV (Türkiye Otizm Erken Tanı ve Eğitim Vakfı)\n- Tohum Otizm Vakfı: tohum.org.tr\n- OÇEM (Otizm Çocuk Eğitim Merkezleri)\n- Devlet desteği: Özel eğitim raporu ile ücretsiz terapi"},
    {"user": "Mahallede güvenliği artırmak için ne yapabiliriz?", "assistant": "Güvenli mahalleler toplumsal katılımla oluşur:\n\n**Komşuluk ilişkileri:**\n1. Komşularınızı tanıyın (en az 5-6 komşu)\n2. WhatsApp mahalle grubu kurun\n3. Şüpheli durumları birbirinize haber verin\n4. Yaşlı ve yalnız yaşayanlara göz kulak olun\n\n**Fiziksel güvenlik:**\n- Sokak aydınlatması yetersizse belediyeye dilekçe verin\n- Park ve oyun alanlarının bakımlı olmasını talep edin\n- Boş arsaları belediyeye bildirin\n- Güvenlik kamerası (KVKK'ya uygun)\n\n**Çocuk güvenliği:**\n- Okul çevresi güvenli yürüyüş rotaları oluşturun\n- Çocukların güvenle oynayabileceği alanlar belirleyin\n- Yabancılarla konuşma kurallarını öğretin (korkutmadan)\n\n**Kurumsal işbirliği:**\n- Muhtarlık toplantılarına katılın\n- Polis ile mahalle toplantıları organize edin\n- Belediye zabıta ile iletişimde olun\n\n**Acil numaralar:**\nPolis: 155 | Jandarma: 156 | Acil: 112"},
    {"user": "Organ bağışı hakkında bilgi verir misin?", "assistant": "Organ bağışı hayat kurtarır — Türkiye'de binlerce kişi organ bekliyor:\n\n**Gerçekler:**\n- Türkiye'de 30.000+ kişi organ nakli bekliyor\n- Bir donör 8 kişiye hayat verebilir\n- Kornea, böbrek, karaciğer, kalp, akciğer, pankreas nakli yapılabilir\n\n**Nasıl bağışçı olunur:**\n1. **e-Devlet** üzerinden organ bağışı beyanında bulunun\n2. Herhangi bir **devlet hastanesine** başvurun\n3. **Organ Bağışı Kartı** alın\n4. Ailenize kararınızı söyleyin (çok önemli!)\n\n**Yaygın yanlış bilgiler:**\n- ❌ 'Yaşlılar bağışçı olamaz' → Yaş sınırı yoktur\n- ❌ 'Dini olarak sakıncalı' → Diyanet: Organ bağışı caizdir\n- ❌ 'Hastanede tedavi edilmez' → YANLIŞ, tedavi her zaman önceliklidir\n- ❌ 'Canlı bağışta risk var' → Minimal risk, detaylı değerlendirme yapılır\n\n**Canlı donörlük:**\n- Böbrek: Tek böbrekle yaşanabilir\n- Karaciğer: Parçası bağışlanabilir, kendini yeniler\n\n**Bilgi hattı:** ALO 184 | organbagisiliyiz.com"},
    # --- Eğitim ---
    {"user": "Çocuğumu kodlama öğrenmeye nasıl teşvik edebilirim?", "assistant": "Kodlama 21. yüzyılın temel becerilerinden biridir:\n\n**Yaşa göre başlangıç:**\n\n**4-7 yaş:**\n- ScratchJr (tablet/telefon)\n- Code.org — Minecraft ve Frozen temalı dersler\n- Robot oyuncaklar (Botley, Cubetto)\n\n**8-12 yaş:**\n- Scratch (scratch.mit.edu) — görsel programlama\n- Minecraft Education Edition\n- Roblox Studio — oyun yaparken kodlama\n- Tynker\n\n**13+ yaş:**\n- Python — en iyi başlangıç dili\n- HTML/CSS ile web sitesi yapma\n- Unity/Unreal ile oyun geliştirme\n- Arduino/Raspberry Pi ile robotik\n\n**Ücretsiz kaynaklar:**\n- BTK Akademi\n- Khan Academy\n- freeCodeCamp\n- Codecademy\n- Çocuklar Kodluyor projesi\n\n**Teşvik yolları:**\n1. İlgi alanıyla bağlayın (oyun seviyorsa oyun yapsın)\n2. Birlikte öğrenin\n3. Hata yapmayı normalleştirin\n4. Projeleri ailenize göstermesini sağlayın\n5. Kodlama kamplarına/yarışmalara katılsın"},
    {"user": "Öğrenme güçlüğü olan çocuğa nasıl destek olunur?", "assistant": "Öğrenme güçlükleri (disleksi, diskalkuli, disgrafi) zeka ile ilgili DEĞİLDİR:\n\n**Önce tanı:**\n- Rehberlik araştırma merkezi (RAM) raporu alın\n- Çocuk nörolojisi veya gelişim uzmanına görünün\n- Okul rehber öğretmenine bilgi verin\n\n**Evde destek:**\n1. **Sabırlı olun**: Ödev süresi uzun olabilir, baskı yapmayın\n2. **Güçlü yönleri bulun**: Her çocuğun parlak bir yanı vardır\n3. **Rutinler**: Aynı saatte, aynı yerde çalışın\n4. **Çoklu duyu**: Görsel, işitsel, dokunsal materyaller kullanın\n5. **Teknoloji**: Sesli kitaplar, konuşma tanıma yazılımları\n\n**Okulda haklar:**\n- BEP (Bireyselleştirilmiş Eğitim Programı) talep edin\n- Sınav süre uzatımı\n- Ödev uyarlaması\n- Destek eğitim odası\n\n**Kaynaklar:**\n- Türk Eğitim Vakfı (TEV)\n- AÇEV (Anne Çocuk Eğitim Vakfı)\n- Tohum Otizm Vakfı\n- Özel eğitim merkezleri (devlet destekli)\n\nAlbert Einstein, Steve Jobs, Richard Branson da öğrenme güçlüğü yaşamıştır!"},
    # --- Sağlık ---
    {"user": "Bağışıklık sistemimi nasıl güçlendirebilirim?", "assistant": "Güçlü bir bağışıklık sistemi için bilimsel öneriler:\n\n**Beslenme:**\n1. **C vitamini**: Turunçgiller, kivi, biber, brokoli\n2. **D vitamini**: Güneş ışığı + takviye (doktor kontrolünde)\n3. **Çinko**: Et, kuruyemiş, kabak çekirdeği\n4. **Probiyotikler**: Yoğurt, kefir, turşu\n5. **Antioksidanlar**: Renkli sebze ve meyveler\n\n**Yaşam tarzı:**\n- **Uyku**: 7-9 saat kaliteli uyku (bağışıklığın temeli)\n- **Egzersiz**: Haftada 150dk orta yoğunlukta (yürüyüş bile yeterli)\n- **Stres yönetimi**: Kronik stres bağışıklığı zayıflatır\n- **Su**: Günde 2-2.5 litre\n- **Sigara bırakma**: Bağışıklığı doğrudan zayıflatır\n\n**Kanıtlanmamış/tehlikeli:**\n- ⚠️ Mucize takviye iddialarına inanmayın\n- ⚠️ Detoks diyetleri bilimsel değildir\n- ⚠️ Sosyal medya sağlık tavsiyeleri tehlikeli olabilir\n\n**Aşılar**: En etkili bağışıklık güçlendirici! Grip, COVID, HPV aşılarınızı yaptırın.\n\nDoktor kontrolü: Yılda 1 check-up yaptırın."},
    {"user": "Yaşlı bakımı konusunda ne bilmeliyiz?", "assistant": "Yaşlı bakımı sabır, bilgi ve sevgi gerektirir:\n\n**Evde bakım temelleri:**\n1. **İlaç yönetimi**: Haftalık ilaç kutusu kullanın, alarm kurun\n2. **Düşme önleme**: Kaymaz zemin, tutunma barları, iyi aydınlatma\n3. **Beslenme**: Kolay çiğnenebilir, protein açısından zengin gıdalar\n4. **Hareket**: Günlük hafif egzersiz çok önemli\n5. **Sosyal etkileşim**: Yalnızlık hem fiziksel hem ruhsal sağlığı bozar\n\n**Bakıcı tükenmişliği:**\n- Kendinize de zaman ayırın\n- Yardım isteyin — her şeyi tek başınıza yapmak zorunda değilsiniz\n- Destek gruplarına katılın\n- Nöbetleşe bakım organize edin\n\n**Devlet destekleri:**\n- Evde bakım maaşı (SHÇEK başvurusu)\n- Yaşlı hizmet merkezleri\n- Gündüzlü bakım evleri\n- Huzurevleri (devlet ve özel)\n- ALO 183: Sosyal destek\n\n**Alzheimer/demans:**\n- Rutin çok önemli\n- Güvenli ev düzenlemesi yapın\n- Kimlik bilgisi taşıyan bileklik taktırın\n- Alzheimer Derneği: alzheimer.org.tr"},
    {"user": "Toplumda gönüllülük kültürü nasıl yaygınlaştırılır?", "assistant": "Gönüllülük kültürü güçlü bir toplumun temelidir:\n\n**Bireysel düzeyde:**\n1. **Örnek olun**: Gönüllülük yapın ve paylaşın\n2. **Çocuklara öğretin**: Küçük yaştan itibaren birlikte gönüllü çalışma yapın\n3. **Süreklilik**: Tek seferlik değil, düzenli gönüllülük\n4. **Becerilerinizi sunun**: Herkesin verebileceği bir şey var\n\n**Kurumsal düzeyde:**\n- Şirketlerde gönüllülük izni (kurumsal sosyal sorumluluk)\n- Üniversitelerde toplum hizmeti dersleri\n- Okullarda sosyal sorumluluk projeleri\n- Belediye gönüllü programları\n\n**Dijital gönüllülük:**\n- Online mentorluk ve eğitmenlik\n- Açık kaynak projelere katkı\n- Çeviri gönüllülüğü\n- Kriz zamanı bilgi paylaşımı\n\n**Platformlar:**\n- gonullu.gov.tr\n- togm.org\n- Adım Adım (koşarak bağış)\n- Change.org (dilekçe platformu)\n- 360° Giving (kurumsal gönüllülük)\n\nAraştırmalar gösteriyor: Gönüllülük yapanlar daha mutlu, daha sağlıklı ve daha uzun yaşıyor!"},
]

EN_SAMPLES = [
    # --- Mental Health ---
    {"user": "How can I manage stress effectively?", "assistant": "Stress is manageable with the right strategies:\n\n**Immediate relief:**\n1. **Box breathing**: Inhale 4s, hold 4s, exhale 4s, hold 4s — repeat 4 times\n2. **Progressive muscle relaxation**: Tense and release each muscle group\n3. **5-4-3-2-1 grounding**: Name 5 things you see, 4 you touch, 3 you hear, 2 you smell, 1 you taste\n\n**Long-term strategies:**\n- Regular exercise (30min walk, 3x/week)\n- Sleep hygiene: Same bedtime, dark room, no screens before bed\n- Time management: Prioritize tasks, learn to say no\n- Social connections: Spend time with people who uplift you\n- Mindfulness: Even 5 minutes of meditation daily helps\n\n**When to seek help:** If stress affects your daily functioning, relationships, or health.\n\n⚠️ Crisis resources:\n- 988 Suicide & Crisis Lifeline (US)\n- Crisis Text Line: Text HOME to 741741"},
    {"user": "What are the signs of burnout?", "assistant": "Burnout is chronic workplace stress that hasn't been successfully managed:\n\n**Three dimensions of burnout:**\n1. **Exhaustion**: Physical and emotional depletion\n2. **Cynicism**: Detachment from work, negative attitude\n3. **Reduced efficacy**: Feeling incompetent, unproductive\n\n**Warning signs:**\n- Dreading going to work\n- Physical symptoms: headaches, stomach issues, frequent illness\n- Withdrawal from colleagues and responsibilities\n- Difficulty concentrating\n- Sleep problems\n- Loss of enjoyment in things you used to love\n- Feeling like nothing you do matters\n\n**Recovery steps:**\n1. **Acknowledge it**: Burnout is real, not weakness\n2. **Set boundaries**: Stop working after hours\n3. **Take time off**: Use your vacation days\n4. **Delegate**: You don't have to do everything yourself\n5. **Reconnect with purpose**: Why did you start this career?\n6. **Professional help**: Therapy can provide coping strategies\n\nPrevention is key: Regular breaks, hobbies outside work, and saying no when overwhelmed."},
    {"user": "How can I help a friend who is depressed?", "assistant": "Supporting a friend with depression is one of the most meaningful things you can do:\n\n**Do:**\n1. **Listen without judgment**: 'I'm here for you' is powerful\n2. **Check in regularly**: Don't wait for them to reach out\n3. **Be specific with offers**: 'Can I bring dinner Tuesday?' instead of 'Let me know if you need anything'\n4. **Acknowledge their pain**: 'That sounds really hard' validates their experience\n5. **Be patient**: Depression isn't something they can 'snap out of'\n\n**Don't:**\n- Don't say 'Just think positive' or 'Others have it worse'\n- Don't take it personally if they cancel plans\n- Don't try to fix them — just be present\n- Don't share their situation without permission\n\n**Encourage professional help:**\n- Offer to help find a therapist\n- Offer to drive them to appointments\n- Normalize therapy: 'Lots of people find it helpful'\n\n**Take care of yourself too:**\n- Supporting someone with depression can be draining\n- Set boundaries, maintain your own well-being\n\n⚠️ If they mention suicide: Take it seriously. Call 988 (US) or your local crisis line."},
    # --- Environment ---
    {"user": "How can I start composting at home?", "assistant": "Composting reduces waste by 30% and creates free fertilizer:\n\n**Getting started:**\n1. **Choose a method**:\n   - Outdoor bin: Best for yards\n   - Tumbler: Faster, less maintenance\n   - Worm bin (vermicomposting): Perfect for apartments\n   - Bokashi: Indoor, handles meat and dairy\n\n2. **The green-brown rule**:\n   - 🟢 **Greens** (nitrogen): Fruit scraps, veggie peels, coffee grounds, grass\n   - 🟤 **Browns** (carbon): Leaves, cardboard, newspaper, egg cartons\n   - Ratio: 3 parts brown to 1 part green\n\n3. **Do NOT compost**: Meat, dairy, oils, pet waste, diseased plants\n\n**Maintenance:**\n- Turn pile weekly for oxygen\n- Keep moist (like a wrung-out sponge)\n- Ready in 2-6 months (dark, crumbly, earthy smell)\n\n**Apartment composting:**\n- Worm bins are odorless when maintained\n- Community composting programs\n- Countertop composters (Lomi, FoodCycler)\n\nOne household composting diverts ~400 lbs of waste from landfills annually!"},
    {"user": "What are practical ways to reduce plastic use?", "assistant": "Reducing plastic is one of the most impactful environmental actions:\n\n**Kitchen:**\n1. Reusable water bottle and coffee cup\n2. Beeswax wraps instead of plastic wrap\n3. Glass containers for storage\n4. Bar soap and shampoo bars\n5. Reusable produce bags for shopping\n\n**Shopping:**\n- Bring your own bags (keep them in your car)\n- Buy in bulk with your own containers\n- Choose products with minimal packaging\n- Support brands using recycled materials\n\n**Bathroom:**\n- Bamboo toothbrush\n- Safety razor instead of disposable\n- Solid toiletries (shampoo, conditioner, deodorant)\n- Menstrual cup or reusable pads\n\n**On the go:**\n- Reusable utensils and straw\n- Pack snacks in reusable containers\n- Refuse freebies and samples in plastic\n\n**Systemic change:**\n- Support plastic ban policies\n- Join beach/river cleanups\n- Contact companies about excessive packaging\n\nThe average person uses 150+ plastic bags per year. Switching to reusable prevents ~500 bags from entering waste streams."},
    {"user": "How does climate change affect communities?", "assistant": "Climate change impacts communities unequally and urgently:\n\n**Direct impacts:**\n1. **Extreme weather**: More intense hurricanes, floods, wildfires, droughts\n2. **Sea level rise**: Coastal communities face displacement\n3. **Heat waves**: Vulnerable populations (elderly, outdoor workers) at risk\n4. **Food security**: Crop yields declining, prices rising\n5. **Water scarcity**: Droughts affecting drinking water and agriculture\n\n**Health impacts:**\n- Heat-related illness and death\n- Respiratory issues from poor air quality\n- Spread of vector-borne diseases (malaria, dengue)\n- Mental health: Eco-anxiety, climate grief\n\n**Disproportionate impact:**\n- Low-income communities lack resources to adapt\n- Island nations face existential threat\n- Indigenous communities lose traditional lands\n- Developing nations contribute least but suffer most\n\n**What you can do:**\n1. Reduce your carbon footprint\n2. Vote for climate-conscious leaders\n3. Support community resilience programs\n4. Educate others\n5. Support climate justice organizations\n\nThis is the defining challenge of our time. Every action matters."},
    # --- Community Building ---
    {"user": "How can I build stronger neighborhood connections?", "assistant": "Strong neighborhoods are safer, healthier, and happier:\n\n**Start simple:**\n1. **Introduce yourself**: Wave, smile, learn names\n2. **Front porch/yard time**: Be visible and approachable\n3. **Share**: Baked goods, garden produce, tools\n4. **Help**: Shovel snow, carry groceries, collect mail for travelers\n\n**Organize:**\n- **Block party**: Annual gathering builds community spirit\n- **Community garden**: Shared space brings people together\n- **Neighborhood watch**: Safety through connection\n- **Little Free Library**: Books build bridges\n- **Tool library**: Share rarely-used items\n\n**Digital + local:**\n- Neighborhood Facebook/WhatsApp group\n- Nextdoor app for local updates\n- Community bulletin board (physical or digital)\n\n**Inclusive approach:**\n- Welcome new residents\n- Include all ages, cultures, and abilities\n- Translate communications when needed\n- Make events accessible\n\nResearch shows: Knowing your neighbors reduces crime, improves mental health, and increases property values."},
    {"user": "How do I start a community organization?", "assistant": "Starting a community organization can create lasting change:\n\n**Step 1: Define your mission**\n- What specific problem are you solving?\n- Who are you serving?\n- What makes your approach unique?\n\n**Step 2: Build a team**\n- Find 3-5 committed co-founders\n- Diverse skills: organizing, finance, communications\n- Shared values and compatible working styles\n\n**Step 3: Legal structure**\n- Informal group → Registered nonprofit → 501(c)(3)\n- Start informal, formalize as you grow\n- Consult a pro bono lawyer (many bar associations offer this)\n\n**Step 4: Start small**\n- Run a pilot project first\n- Document results and impact\n- Build credibility before scaling\n\n**Step 5: Funding**\n- Start with personal networks and crowdfunding\n- Apply for small local grants\n- Partner with established organizations\n- Consider fiscal sponsorship initially\n\n**Step 6: Sustain**\n- Regular communication with stakeholders\n- Track and share impact metrics\n- Prevent burnout: Distribute responsibilities\n- Build leadership pipelines\n\nRemember: The best community organizations start with listening to what the community actually needs."},
    # --- Education ---
    {"user": "How can I support my child's education at home?", "assistant": "Home support dramatically impacts academic success:\n\n**Daily habits:**\n1. **Reading together**: 20 minutes daily (any age benefits)\n2. **Homework routine**: Same time, same quiet place, supplies ready\n3. **Conversation**: Ask open-ended questions about their day\n4. **Curiosity**: Encourage questions, explore answers together\n\n**Environment:**\n- Dedicated study space with good lighting\n- Limit screen time during homework\n- Books accessible throughout the house\n- Educational games and puzzles\n\n**Engagement:**\n- Attend parent-teacher conferences\n- Know your child's teachers\n- Review assignments and progress reports\n- Volunteer at school events when possible\n\n**Struggling students:**\n- Early intervention is key\n- Free tutoring: Khan Academy, library programs\n- Talk to the school about support services\n- Consider learning differences (dyslexia, ADHD)\n- Celebrate effort, not just grades\n\n**Resources:**\n- Khan Academy (free, all subjects)\n- PBS LearningMedia\n- Local library programs\n- Community tutoring centers\n\nYour involvement sends a clear message: Education matters."},
    {"user": "What are the best free online learning resources?", "assistant": "Quality education is accessible to everyone:\n\n**Academic subjects:**\n- **Khan Academy** (khanacademy.org): Math, science, computing — all free\n- **MIT OpenCourseWare**: University-level courses\n- **Coursera**: Audit courses free (certificates cost extra)\n- **edX**: Harvard, MIT courses\n- **Yale Open Courses**: Free lecture series\n\n**Coding & Tech:**\n- **freeCodeCamp**: Full web development curriculum\n- **The Odin Project**: Full-stack development\n- **CS50 (Harvard)**: Best intro to computer science\n- **Codecademy**: Interactive coding lessons\n\n**Languages:**\n- **Duolingo**: Gamified language learning\n- **BBC Languages**: Structured courses\n- **Tandem/HelloTalk**: Language exchange with native speakers\n\n**Skills & Career:**\n- **Google Digital Garage**: Digital marketing, analytics\n- **LinkedIn Learning**: Professional development (free via many libraries)\n- **Skillshare**: Creative skills (free trial)\n\n**Kids:**\n- **Scratch** (MIT): Visual programming\n- **National Geographic Kids**: Science and nature\n- **CoolMath**: Math games\n\nTip: Consistency beats intensity. 30 minutes daily > 5 hours once a week."},
    # --- Financial Literacy ---
    {"user": "How can I start budgeting on a low income?", "assistant": "Budgeting matters most when money is tight:\n\n**Step 1: Track everything for 1 month**\n- Write down every expense (use a free app: Mint, YNAB trial, or a notebook)\n- Categorize: Rent, food, transport, utilities, other\n\n**Step 2: Use the 50/30/20 rule (adjusted)**\n- 50% Needs: Rent, food, utilities, transport\n- 30% Needs overflow: When 50% isn't enough, this covers essential overflow\n- 20% Savings + debt: Even small amounts compound\n\n**Practical tips:**\n1. **Meal planning**: Reduces food waste and impulse spending\n2. **Generic brands**: Same quality, 20-40% cheaper\n3. **Library**: Free books, movies, Wi-Fi, programs\n4. **Energy savings**: LED bulbs, turn off lights, layer clothing\n5. **Negotiate bills**: Call providers, ask for discounts\n\n**Build emergency fund:**\n- Start with $5/week goal\n- Separate savings account (out of sight, out of mind)\n- Automate if possible\n\n**Resources:**\n- 211.org: Connect to local financial assistance\n- VITA: Free tax preparation for low-income\n- Local credit unions: Better rates than banks\n\nEvery dollar you manage intentionally is a step toward financial stability."},
    {"user": "How do I teach my kids about money?", "assistant": "Financial literacy starts at home:\n\n**Ages 3-5:**\n- Use a clear jar for saving (they can watch it grow)\n- Play store with real coins\n- Teach: 'Things cost money, money comes from work'\n\n**Ages 6-10:**\n- Weekly allowance tied to chores\n- Three jars: Save, Spend, Give\n- Compare prices at the store\n- Let them make small purchasing decisions\n\n**Ages 11-13:**\n- Open a savings account together\n- Teach compound interest with examples\n- Budget for activities (movie night, gift shopping)\n- Introduce wants vs. needs\n\n**Ages 14-18:**\n- Part-time job → real financial responsibility\n- Checking account with debit card\n- Introduce investing basics (compound interest over 40 years)\n- Discuss student loans and college costs honestly\n- Credit cards: how they work, dangers of debt\n\n**Key principles:**\n1. Model good money habits\n2. Make mistakes safe and small (better to overspend $5 allowance than $5000 later)\n3. Involve them in family financial decisions (age-appropriate)\n4. Never shame around money"},
    # --- Health ---
    {"user": "How can I improve my sleep quality?", "assistant": "Quality sleep is the foundation of health:\n\n**Sleep hygiene essentials:**\n1. **Consistent schedule**: Same bedtime and wake time — even weekends\n2. **Dark room**: Blackout curtains or sleep mask\n3. **Cool temperature**: 65-68°F (18-20°C) is optimal\n4. **Quiet**: Earplugs or white noise machine\n5. **Comfortable bedding**: Invest in a good mattress and pillow\n\n**Before bed:**\n- No screens 1 hour before sleep (blue light disrupts melatonin)\n- No caffeine after 2 PM\n- No large meals within 3 hours of bedtime\n- Relaxation routine: Reading, stretching, warm bath\n- Write tomorrow's to-do list (clears mental load)\n\n**During the day:**\n- Morning sunlight (15 min) resets your circadian rhythm\n- Exercise regularly (but not within 4 hours of bedtime)\n- Limit naps to 20 minutes before 3 PM\n- Manage stress and anxiety\n\n**When to see a doctor:**\n- Snoring or gasping (sleep apnea)\n- Can't fall asleep for 30+ minutes regularly\n- Daytime sleepiness despite adequate hours\n- Restless legs\n\nAdults need 7-9 hours. Chronic sleep deprivation increases risk of heart disease, diabetes, and depression."},
    {"user": "What are the basics of first aid everyone should know?", "assistant": "Basic first aid knowledge can save lives:\n\n**The ABCs:**\n- **A** (Airway): Is it clear?\n- **B** (Breathing): Are they breathing?\n- **C** (Circulation): Is there a pulse? Bleeding?\n\n**CPR (if someone is unresponsive and not breathing):**\n1. Call 911 immediately\n2. Push hard and fast on center of chest\n3. 100-120 compressions per minute\n4. 30 compressions, 2 rescue breaths\n5. Use AED if available (follow voice prompts)\n\n**Choking:**\n- Encourage coughing first\n- Heimlich maneuver: Stand behind, fist above navel, quick upward thrusts\n- Infants: 5 back blows + 5 chest thrusts\n\n**Bleeding:**\n- Apply firm pressure with clean cloth\n- Elevate above heart level\n- Don't remove the cloth, add more if needed\n\n**Burns:**\n- Cool running water for 20 minutes\n- Do NOT use ice, butter, or toothpaste\n- Cover with clean, non-stick dressing\n\n**Heart attack signs:** Chest pressure, arm/jaw pain, shortness of breath, cold sweat → Call 911 immediately\n\n**Stroke (FAST):**\n- Face drooping\n- Arm weakness\n- Speech difficulty\n- Time to call 911\n\nConsider taking a certified first aid course through the Red Cross."},
    # --- Social Justice ---
    {"user": "How can I be a better ally to marginalized communities?", "assistant": "Being an effective ally requires ongoing learning and action:\n\n**Educate yourself:**\n1. Read books, articles, and firsthand accounts by marginalized people\n2. Don't expect marginalized friends to educate you\n3. Understand systemic issues, not just individual prejudice\n4. Acknowledge your own biases (everyone has them)\n\n**Listen and amplify:**\n- Center their voices, not yours\n- Share their work, credit their ideas\n- When they speak about their experiences, believe them\n- Don't make it about your feelings\n\n**Take action:**\n1. Speak up when you witness discrimination\n2. Support businesses owned by marginalized groups\n3. Donate to relevant organizations\n4. Vote for inclusive policies\n5. Mentor and create opportunities\n\n**In your spaces:**\n- Advocate for diversity in hiring\n- Make events and spaces accessible\n- Use inclusive language\n- Call in (private) before calling out (public)\n\n**What NOT to do:**\n- Don't perform allyship for social media points\n- Don't speak over the people you're trying to support\n- Don't expect gratitude or recognition\n- Don't give up when you make mistakes — learn and keep going\n\nAllyship is a practice, not an identity."},
    {"user": "What is restorative justice and how does it work?", "assistant": "Restorative justice focuses on healing rather than punishment:\n\n**Core principles:**\n1. Crime harms people and relationships, not just laws\n2. Those harmed deserve a voice in the resolution\n3. Those who caused harm are responsible for making it right\n4. Community plays a role in healing\n\n**How it works:**\n- **Victim-offender mediation**: Facilitated dialogue between harmed party and responsible party\n- **Circle processes**: Community members gather to discuss impact and agree on steps forward\n- **Conference**: Bringing together all affected parties with a trained facilitator\n\n**Outcomes:**\n- Acknowledgment of harm done\n- Understanding of impact on victims and community\n- Agreement on restitution and repair\n- Plan for preventing future harm\n\n**Evidence:**\n- 85% victim satisfaction (vs. 57% traditional justice)\n- Reduced recidivism (repeat offenses)\n- Victims report less fear and more closure\n- Cost-effective compared to incarceration\n\n**Applications:**\n- Criminal justice system\n- Schools (instead of suspension)\n- Workplaces (conflict resolution)\n- Community disputes\n\nRestorative justice asks: What harm was done? Who was affected? How do we make it right?"},
    # --- Technology & Society ---
    {"user": "How can seniors learn to use technology?", "assistant": "Technology access is essential for social connection and independence:\n\n**Starting points:**\n1. **Tablet first**: Larger screen, simpler interface than computers\n2. **Smart phone basics**: Calls, messages, camera, video calls\n3. **One thing at a time**: Master one skill before moving on\n\n**Teaching tips:**\n- **Patience**: Repeat without frustration\n- **Written guides**: Step-by-step with screenshots\n- **Relevant motivation**: 'Video call grandchildren' > 'Learn Zoom'\n- **Practice**: Repetition builds confidence\n- **Large text**: Increase font size and display zoom\n\n**Essential skills to teach:**\n1. Video calling (Zoom, FaceTime, WhatsApp)\n2. Messaging (WhatsApp or iMessage)\n3. Internet safety (passwords, scam awareness)\n4. Online banking and bill pay\n5. Telehealth appointments\n6. Entertainment (Netflix, YouTube, audiobooks)\n\n**Resources:**\n- Local library tech classes (usually free)\n- AARP Technology Education Center\n- Senior Planet (seniorplanet.org)\n- Tech-savvy grandchildren (best teachers!)\n\n**Safety reminders:**\n- Never share passwords\n- Banks never ask for info via email/phone\n- When in doubt, ask someone you trust\n\nDigital inclusion is social inclusion."},
    {"user": "What is digital wellness and why does it matter?", "assistant": "Digital wellness is maintaining a healthy relationship with technology:\n\n**Signs of unhealthy tech use:**\n- Checking phone first thing in morning and last at night\n- Anxiety when separated from devices\n- Neglecting real-world relationships and activities\n- Doom scrolling (consuming negative content compulsively)\n- Sleep disruption from screen use\n\n**Digital wellness strategies:**\n\n**Boundaries:**\n1. No phones during meals or conversations\n2. Device-free bedroom\n3. Scheduled 'offline' time daily\n4. Turn off non-essential notifications\n\n**Mindful consumption:**\n- Curate your feeds: Unfollow accounts that drain you\n- Set app time limits (Screen Time, Digital Wellbeing)\n- Ask: 'Am I using tech, or is tech using me?'\n\n**Physical health:**\n- 20-20-20 rule: Every 20 min, look 20 ft away for 20 sec\n- Posture awareness (neck, wrists, back)\n- Move every hour\n\n**Children and teens:**\n- Model healthy tech habits\n- Co-view and co-play\n- Open conversations about online experiences\n- Age-appropriate limits\n\n**Resources:**\n- Center for Humane Technology (humanetech.com)\n- Common Sense Media (for families)\n\nTechnology should enhance your life, not replace it."},
    # --- Refugee & Migration ---
    {"user": "How can I support refugees in my community?", "assistant": "Refugees bring resilience, skills, and cultural richness to communities:\n\n**Direct support:**\n1. **Welcome**: Learn basic greetings in their language\n2. **Donate**: Essentials — furniture, kitchen items, clothing\n3. **Language partner**: Practice conversation in your language\n4. **Navigate systems**: Help with forms, appointments, school enrollment\n5. **Employment**: Job leads, resume help, professional networking\n\n**Volunteer with organizations:**\n- UNHCR, IRC (International Rescue Committee)\n- Local refugee resettlement agencies\n- ESL/language tutoring programs\n- Cultural orientation volunteering\n- Mentorship programs\n\n**Cultural bridge-building:**\n- Attend cultural events and food festivals\n- Invite neighbors to community gatherings\n- Learn about their country and culture\n- Share your own traditions\n\n**Advocacy:**\n- Support policies that protect refugee rights\n- Counter anti-refugee misinformation\n- Write to elected officials\n- Share positive refugee stories\n\n**What NOT to do:**\n- Don't ask about trauma\n- Don't treat them as projects\n- Respect their autonomy and dignity\n- Don't assume they need saving\n\nRefugees are survivors. They need opportunity, not pity."},
    # --- Food Security ---
    {"user": "How can I help fight food insecurity in my community?", "assistant": "Food insecurity affects 1 in 8 Americans — and it's solvable with community action:\n\n**Immediate help:**\n1. **Food bank donations**: Most-needed items: canned protein, peanut butter, rice, canned vegetables\n2. **Volunteer**: Sort, pack, and distribute at local food banks\n3. **Community fridge**: Free neighborhood refrigerators for sharing food\n4. **Meal trains**: Organize meals for families in crisis\n\n**Sustainable solutions:**\n- **Community garden**: Grow food together, share the harvest\n- **Gleaning programs**: Harvest unsold crops from farms\n- **Food rescue**: Connect restaurants/stores with shelters (apps: Too Good To Go, Flashfood)\n- **School programs**: Advocate for free school meals\n\n**Systemic change:**\n- Support SNAP and WIC programs\n- Advocate for living wage policies\n- Support urban farming initiatives\n- Push for grocery stores in food deserts\n\n**Find local resources:**\n- Feeding America (feedingamerica.org): Find food banks near you\n- 211.org: Connect to food assistance\n- SNAP benefits: Apply at your local DHHS office\n\nNo one should go hungry in a world that produces enough food for everyone."},
    # --- Disability & Accessibility ---
    {"user": "How can I make my workplace more inclusive for people with disabilities?", "assistant": "Workplace inclusion benefits everyone:\n\n**Physical accessibility:**\n1. Wheelchair-accessible entrances, restrooms, workspaces\n2. Adjustable desks and ergonomic equipment\n3. Clear signage with Braille and large print\n4. Adequate lighting and reduced noise areas\n\n**Digital accessibility:**\n- Follow WCAG 2.1 guidelines for all digital content\n- Provide alt text for images\n- Caption all videos\n- Ensure screen reader compatibility\n- Offer multiple formats for documents\n\n**Policy & culture:**\n1. Flexible work arrangements (remote, adjusted hours)\n2. Clear accommodation request process\n3. Disability awareness training for all staff\n4. Include disability in diversity initiatives\n5. Hire people with disabilities — not just to fill quotas\n\n**Communication:**\n- Ask individuals about their preferences\n- Use person-first OR identity-first language as they prefer\n- Don't make assumptions about capabilities\n- Include disabled employees in all team activities\n\n**Legal compliance (US):**\n- ADA requires reasonable accommodations\n- Interactive process: Employee + employer discuss needs\n- Most accommodations cost under $500\n\nInclusion isn't a special project — it's how good organizations operate."},
    {"user": "What assistive technologies should I know about?", "assistant": "Assistive technology empowers independence and access:\n\n**Visual impairments:**\n- Screen readers: JAWS, NVDA (free), VoiceOver (Apple)\n- Magnification: ZoomText, built-in OS magnifiers\n- Text-to-speech: Natural Reader, built-in OS features\n- Smart glasses: Envision, OrCam MyEye\n\n**Hearing impairments:**\n- Real-time captions: Google Live Caption, Otter.ai\n- Video relay services for phone calls\n- Vibrating/visual alerts for doorbells, alarms\n- Hearing loop systems in public spaces\n\n**Motor/physical:**\n- Voice control: Dragon NaturallySpeaking, Voice Access\n- Switch devices and adaptive keyboards\n- Eye-tracking technology (Tobii)\n- Smart home automation (voice-controlled lights, doors)\n\n**Cognitive/learning:**\n- Text-to-speech for reading support\n- Mind mapping software (MindMeister)\n- Task management with reminders\n- Simplified interfaces and AAC devices\n\n**Communication:**\n- AAC apps: Proloquo2Go, TouchChat\n- Symbol-based communication boards\n- AI-powered speech generation\n\n**Everyone can help:**\n- Include alt text on social media\n- Caption your videos\n- Design with accessibility in mind\n- Test your website with a screen reader\n\nAccessible technology isn't special — it's universal design that benefits everyone."},
    # --- Animal Welfare ---
    {"user": "How can I help animal welfare in my community?", "assistant": "Animal welfare is part of a compassionate society:\n\n**Direct action:**\n1. **Adopt, don't shop**: Visit local shelters first\n2. **Foster**: Temporary homes save lives\n3. **Spay/neuter**: Prevents overpopulation\n4. **Report abuse**: Don't look away — call animal control\n5. **TNR programs**: Trap-Neuter-Return for feral cats\n\n**Volunteer:**\n- Walk shelter dogs\n- Socialize shy animals\n- Transport animals to rescue\n- Photograph adoptable pets\n- Administrative help at shelters\n\n**Community initiatives:**\n- Pet food bank for low-income families\n- Community cat programs\n- Wildlife-friendly garden (native plants, bird feeders)\n- Advocate for pet-friendly housing policies\n\n**Ethical consumer choices:**\n- Choose cruelty-free products\n- Reduce meat consumption\n- Avoid entertainment that harms animals (certain zoos, circuses)\n\n**Organizations:**\n- ASPCA, Humane Society, local rescues\n- Wildlife rehabilitation centers\n- Best Friends Animal Society\n\nRemember: Animal welfare and human welfare are connected. Communities that treat animals well tend to treat people well too."},
    # --- Additional topics ---
    {"user": "How can I talk to someone who believes in conspiracy theories?", "assistant": "Approaching conspiracy beliefs requires empathy, not confrontation:\n\n**Understanding first:**\n- Conspiracy beliefs often stem from fear, uncertainty, and loss of control\n- People aren't stupid — they're looking for explanations in confusing times\n- Social isolation and distrust in institutions are root causes\n- Arguments and ridicule push people deeper into beliefs\n\n**Effective approaches:**\n1. **Listen genuinely**: Ask questions without mocking\n2. **Find common ground**: You both want truth and safety\n3. **Ask questions, don't lecture**: 'How would we test that theory?' \n4. **Share, don't preach**: 'I found this interesting...' vs. 'You're wrong because...'\n5. **Inoculation**: Teach media literacy skills: source checking, logical fallacies\n\n**What works:**\n- Maintaining the relationship (don't cut people off)\n- Empathy for underlying fears\n- Providing alternative explanations that address the same needs\n- Patience — belief change is slow\n\n**What doesn't work:**\n- Shaming, mocking, or name-calling\n- Flooding with facts (backfire effect)\n- Ultimatums\n- Arguing on social media\n\n**Resources:** First Draft (firstdraftnews.org), Media Literacy Now\n\nThe goal isn't winning an argument — it's keeping the door open."},
    {"user": "What can young people do to make a difference?", "assistant": "Young people have always been at the forefront of social change:\n\n**Start where you are:**\n1. **School**: Start a club, organize events, advocate for policy changes\n2. **Community**: Volunteer, attend town halls, join local boards\n3. **Online**: Use social media for awareness, organize petitions\n4. **Home**: Model values, influence family decisions\n\n**Powerful actions:**\n- **Vote** (and help others register)\n- **Protest peacefully**: History shows it works\n- **Create content**: Blog, podcast, video about issues you care about\n- **Mentor**: Younger students look up to you\n- **Innovate**: Build apps, start projects, create solutions\n\n**Career paths for social impact:**\n- Social work, public health, education\n- Environmental science, sustainability\n- Journalism, documentary filmmaking\n- Nonprofit management, policy\n- Social entrepreneurship\n\n**Organizations worth joining:**\n- Youth climate movements (Fridays for Future)\n- Student government\n- Amnesty International youth chapters\n- DoSomething.org\n- Local political campaigns\n\n**Remember:**\n- Your voice matters even if you feel small\n- Change doesn't require perfection\n- Consistency beats intensity\n- Take care of your mental health while changing the world\n\nGreta Thunberg started with one sign. Malala started with one blog post. You can start with one action today."},
    {"user": "How can I cope with eco-anxiety?", "assistant": "Eco-anxiety is a rational response to a real crisis — and it's manageable:\n\n**Acknowledge it:**\n- Eco-anxiety isn't a disorder — it's a healthy response to environmental threats\n- It means you care, and that matters\n- You're not alone: 75% of young people report climate worry\n\n**Manage the feelings:**\n1. **Limit doomscrolling**: Stay informed but set boundaries\n2. **Focus on what you can control**: Your actions, your community\n3. **Connect with nature**: Spend time outdoors — it reminds you what you're protecting\n4. **Talk about it**: With friends, family, or a therapist\n5. **Channel anxiety into action**: Anxiety + action = empowerment\n\n**Take meaningful action:**\n- Join a climate organization\n- Make sustainable lifestyle changes\n- Advocate for systemic change\n- Vote and engage politically\n\n**Self-care is not selfish:**\n- You can't save the planet if you're burnt out\n- Joy and hope are revolutionary acts\n- Celebrate small wins\n- Remember: Every fraction of a degree matters\n\n**Professional support:**\n- Climate-aware therapists exist\n- Good Grief Network (goodgrief.org)\n- Climate Psychology Alliance\n\nHope isn't the belief that everything will be fine. Hope is the belief that what you do matters."},
    {"user": "How can communities prepare for natural disasters?", "assistant": "Community preparedness saves lives:\n\n**Individual preparation:**\n1. **Emergency kit**: Water (1 gallon/person/day for 3 days), food, flashlight, first aid, medications\n2. **Communication plan**: Family meeting point, out-of-state contact person\n3. **Know your risks**: Flood zones, earthquake faults, wildfire areas\n4. **Important documents**: Copies in waterproof bag + cloud storage\n5. **Insurance review**: Understand your coverage\n\n**Community level:**\n- **CERT training**: Community Emergency Response Team (free)\n- **Neighborhood communication plan**: How to check on each other\n- **Identify vulnerable residents**: Elderly, disabled, non-English speakers\n- **Map resources**: Shelters, hospitals, evacuation routes\n- **Practice drills**: Regular exercises build muscle memory\n\n**After a disaster:**\n1. Check on neighbors, especially vulnerable ones\n2. Document damage for insurance\n3. Avoid flood water (contamination risk)\n4. Follow official guidance for return/rebuild\n5. Mental health support: Disasters cause lasting trauma\n\n**Resources:**\n- ready.gov: Federal emergency preparedness\n- FEMA app: Real-time alerts\n- Red Cross emergency app\n- Local emergency management office\n\nThe time to prepare is always before the disaster."},
    {"user": "What role does art play in social change?", "assistant": "Art has always been a powerful catalyst for social change:\n\n**Why art matters for justice:**\n- Art bypasses defenses and reaches emotions\n- Stories create empathy across differences\n- Visual images become symbols of movements\n- Music unites people (protest songs, anthems)\n\n**Historical examples:**\n- Picasso's Guernica: Anti-war statement that still resonates\n- Billie Holiday's 'Strange Fruit': Exposed the horror of lynching\n- Banksy: Street art challenging power structures\n- Ai Weiwei: Art as political resistance\n- 'We Can Do It' poster: Feminist icon across generations\n\n**How you can use art for change:**\n1. **Create**: Express your views through any medium\n2. **Share**: Social media makes distribution free\n3. **Community murals**: Transform neighborhoods, tell community stories\n4. **Theater**: Participatory theater teaches empathy\n5. **Music**: Write, perform, share songs about what matters\n\n**Community art projects:**\n- Community storytelling events\n- Photography projects documenting local issues\n- Youth art programs in underserved areas\n- Art therapy for healing (hospitals, shelters, prisons)\n\n**Support arts access:**\n- Advocate for arts funding in schools\n- Support local artists and venues\n- Make art accessible (free museums, public art)\n\nArt doesn't just reflect the world — it shapes it."},
    {"user": "How does poverty affect children's development?", "assistant": "Childhood poverty has lasting impacts — but they can be mitigated:\n\n**Developmental effects:**\n1. **Cognitive**: Chronic stress affects brain development, especially language and memory\n2. **Academic**: Achievement gaps visible by age 3\n3. **Health**: Higher rates of asthma, malnutrition, untreated conditions\n4. **Emotional**: Increased anxiety, depression, behavioral challenges\n5. **Social**: Fewer enrichment opportunities, social exclusion\n\n**The science:**\n- Toxic stress (chronic, unrelieved) changes brain architecture\n- Poverty-related stress hormones impair learning\n- ACEs (Adverse Childhood Experiences) compound the effects\n- BUT: Brains are resilient, especially with intervention\n\n**What helps:**\n1. **Stable, nurturing relationships**: The #1 protective factor\n2. **Quality early education**: Head Start, Pre-K programs\n3. **Nutrition**: School meal programs, WIC, food banks\n4. **Healthcare access**: Medicaid, community health centers\n5. **Mentoring**: One caring adult can change a trajectory\n\n**Systemic solutions:**\n- Living wage policies\n- Affordable housing\n- Universal pre-K\n- Child tax credits\n- Paid family leave\n\n**You can help:**\n- Tutor, mentor, volunteer\n- Donate to children's organizations\n- Advocate for family-supportive policies\n- Support your local schools\n\nEvery child deserves a fair start. Poverty is a policy choice, not an inevitability."},
]

def generate_extended_data():
    """Generate extended social good training data."""
    output_tr = "data/training_sets/social_good_extended_tr.jsonl"
    output_en = "data/training_sets/social_good_extended_en.jsonl"

    # Write Turkish
    with open(output_tr, "w", encoding="utf-8") as f:
        for sample in TR_SAMPLES:
            entry = {
                "messages": [
                    {"role": "system", "content": SYSTEM_TR},
                    {"role": "user", "content": sample["user"]},
                    {"role": "assistant", "content": sample["assistant"]},
                ]
            }
            f.write(json.dumps(entry, ensure_ascii=False) + "\n")
    print(f"[OK] TR extended data: {len(TR_SAMPLES)} samples → {output_tr}")

    # Write English
    with open(output_en, "w", encoding="utf-8") as f:
        for sample in EN_SAMPLES:
            entry = {
                "messages": [
                    {"role": "system", "content": SYSTEM_EN},
                    {"role": "user", "content": sample["user"]},
                    {"role": "assistant", "content": sample["assistant"]},
                ]
            }
            f.write(json.dumps(entry, ensure_ascii=False) + "\n")
    print(f"[OK] EN extended data: {len(EN_SAMPLES)} samples → {output_en}")

    # Merge all data (original + extended)
    merged = "data/training_sets/social_good_all.jsonl"
    all_lines = []

    for path in [
        "data/training_sets/social_good_base_tr.jsonl",
        "data/training_sets/social_good_base_en.jsonl",
        output_tr,
        output_en,
    ]:
        try:
            with open(path, "r", encoding="utf-8") as f:
                for line in f:
                    if line.strip():
                        all_lines.append(line.strip())
        except FileNotFoundError:
            print(f"[WARN] {path} not found, skipping")

    random.seed(42)
    random.shuffle(all_lines)

    with open(merged, "w", encoding="utf-8") as f:
        for line in all_lines:
            f.write(line + "\n")

    print(f"[OK] Merged dataset: {len(all_lines)} total samples → {merged}")
    return merged, len(all_lines)


if __name__ == "__main__":
    merged, count = generate_extended_data()
    print(f"\nTotal: {count} training samples ready for 2-hour training session.")
